apiVersion: 1

datasources:
  - name: grafana-athena-datasource
    type: grafana-athena-datasource
    access: proxy
    orgId: 1
    isDefault: true
    jsonData:
      defaultRegion: us-east-1             # ajuste para sua região AWS
      catalog: AwsDataCatalog
      database: default
      workgroup: primary                   # ou outro workgroup
      authType: default
      outputLocation: s3://s3-historico-grafana
    secureJsonData:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
