apiVersion: 1

datasources:
  - name: Athena
    type: grafana-athena-datasource
    access: proxy
    orgId: 1
    isDefault: true
    jsonData:
      defaultRegion: us-east-1
      catalog: AwsDataCatalog
      database: default
      workgroup: primary
      authType: default
      outputLocation: ${ATHENA_OUTPUT_LOCATION}
    secureJsonData:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
