services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - GF_INSTALL_PLUGINS=boazreicher-mosaicplot-panel
    volumes:
      - grafana-storage:/var/lib/grafana
      - ~/grafana-aws/credentials:/root/.aws/credentials:ro
      - ./provisioning:/etc/grafana/provisioning

volumes:
  grafana-storage:

