---
- hosts: grafana
  become: yes

  tasks:
    - name: Atualizar pacotes do sistema
      yum:
        name: "*"
        state: latest

    - name: Instalar pacotes básicos
      yum:
        name:
          - docker
          - python3-pip
        state: present

    - name: Criar diretório para Docker CLI plugins
      file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
        mode: '0755'

    - name: Instalar Docker Compose nativo
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.28.0/docker-compose-linux-x86_64"
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: '0755'

    - name: Instalar módulo Docker do Python
      pip:
        name: docker
        executable: pip3
        extra_args: "--ignore-installed"

    - name: Habilitar e iniciar serviço Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Criar diretório do Grafana
      file:
        path: /opt/grafana
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Copiar código do Grafana
      copy:
        src: "{{ playbook_dir }}/../grafana/"
        dest: /opt/grafana/
        owner: root
        group: root
        mode: 0755

    - name: Copiar arquivo .env
      copy:
        src: "{{ playbook_dir }}/.env"
        dest: /opt/grafana/.env
        owner: root
        group: root
        mode: 0644

    - name: Copiar dashboards para provisioning
      copy:
        src: "{{ playbook_dir }}/../grafana/provisioning/"
        dest: /opt/grafana/provisioning/
        owner: root
        group: root
        mode: 0755

    - name: Subir Grafana via Docker Compose
      community.docker.docker_compose_v2:
        project_src: /opt/grafana
        env_files:
          - /opt/grafana/.env
        state: present
        recreate: always
        remove_orphans: true
