---
- hosts: grafana
  become: yes

  tasks:
    - name: Atualizar pacotes do sistema
      yum:
        name: "*"
        state: latest

    - name: Instalar pacotes básicos
      yum:
        name:
          - docker
          - python3-pip
        state: present

    - name: Instalar módulo Docker do Python
      pip:
        name: docker
        executable: pip3
        extra_args: "--ignore-installed"

    - name: Habilitar e iniciar serviço Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Criar diretório do Grafana
      file:
        path: /opt/grafana
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Copiar código do Grafana
      copy:
        src: "{{ playbook_dir }}/../grafana/"
        dest: /opt/grafana/
        owner: root
        group: root
        mode: 0755

    - name: Copiar arquivo .env
      copy:
        src: "{{ playbook_dir }}/.env"
        dest: /opt/grafana/.env
        owner: root
        group: root
        mode: 0644

 - name: Subir Grafana via Docker Compose
      community.docker.docker_compose:
        project_src: /opt/grafana
        state: present
        restarted: true
